---

- include_tasks: roles/lib/tasks/init_role.yml

- include_tasks: roles/lib/tasks/install_packages.yml

- include_tasks: roles/lib/tasks/create_configs.yml

- include: roles/lib/tasks/enable_service.yml
  
- name: reboot!
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true


  

  
