---

- include_tasks: roles/lib/tasks/init_role.yml
  
- include_tasks: roles/lib/tasks/install_packages.yml
  
- include_tasks: roles/lib/tasks/create_configs.yml

- meta: flush_handlers

- include_tasks: roles/lib/tasks/import_database.yml

#- name: Create database user with name root
#  mysql_user:
#    name=root
#    password={{ openstack_password }}
#    priv=*.*:ALL,GRANT
#    state=present  


