---

component: neutron
service: network
api_port: 9696

packages:
  - neutron-server
  - neutron-plugin-ml2
  - neutron-plugin-openvswitch-agent
  - neutron-l3-agent
  - neutron-dhcp-agent
  - neutron-metadata-agent
  - openvswitch-switch

templates:
  - files:
      - path: /etc/neutron/neutron.conf
      - path: /etc/neutron/plugins/ml2/ml2_conf.ini
      - path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
      - path: /etc/neutron/l3_agent.ini
      - path: /etc/neutron/dhcp_agent.ini
      - path: /etc/neutron/metadata_agent.ini
      - path: /etc/openvswitch_agent.ini
    notify:
      - nova-api restart
      - neutron-server restart
      - neutron-openvswitch-agent restart
      - neutron-dhcp-agent restart
      - neutron-metadata-agent restart
      - neutron-l3-agent restart

db_syncs:
  - command: neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
    become_user: neutron

  

    
