---

- include_tasks: roles/lib/tasks/init_role.yml

- include_tasks: roles/lib/tasks/import_database.yml

- include_tasks: roles/openstack_lib/tasks/add_service.yml

- include_tasks: roles/lib/tasks/install_packages.yml

- include_tasks: roles/lib/tasks/create_configs.yml

- include_tasks: roles/openstack_lib/tasks/service_db_sync.yml

- name: Check the br exists
  shell: ovs-vsctl show | grep br-pppoe
  register: result
  changed_when: false
  failed_when: false
  
- name: ovs-vsctl add-br/port
  shell: '{{ item }}'
  changed_when: false
  when: result.rc
  with_items:
    - 'ovs-vsctl add-br br-pppoe'
    - 'ovs-vsctl add-port br-pppoe {{ ens1 }}'

