---

component: keystone
service: identity
api_port: 9292

packages:
  - acl
  - apache2
  - keystone
  - libapache2-mod-wsgi

templates:
  - files:
      - path: /etc/keystone/keystone.conf
    notify:
      - apache2 restart
      
db_syncs:
  - command: keystone-manage db_sync
    become_user: keystone 

openstack_commands:
  - project create --domain default --description "Service Project" service
  - --os-auth-url http://{{ controller }}:5000/v3 --os-project-domain-name default --os-user-domain-name default --os-project-name admin --os-username admin token issue
  - token issue
  
